import { defineConfig } from '@rslib/core';

const pluginEntries = {
  'plugin/customParseFormat': './src/plugin/customParseFormat.ts',
  'plugin/localeData': './src/plugin/localeData.ts',
  'plugin/localizedFormat': './src/plugin/localizedFormat.ts',
  'plugin/advancedFormat': './src/plugin/advancedFormat.ts',
  'plugin/parserPipeline': './src/plugin/parserPipeline.ts',
  'plugin/tokenRegistry': './src/plugin/tokenRegistry.ts',
  'plugin/utc': './src/plugin/utc.ts',
  'plugin/timezone': './src/plugin/timezone.ts',
  'plugin/relativeTime': './src/plugin/relativeTime.ts',
  'plugin/duration': './src/plugin/duration.ts',
  'plugin/calendar': './src/plugin/calendar.ts',
  'plugin/weekOfYear': './src/plugin/weekOfYear.ts',
  'plugin/isoWeek': './src/plugin/isoWeek.ts',
  'plugin/quarterOfYear': './src/plugin/quarterOfYear.ts',
  'plugin/isBetween': './src/plugin/isBetween.ts',
  'plugin/isSameOrAfter': './src/plugin/isSameOrAfter.ts',
  'plugin/isSameOrBefore': './src/plugin/isSameOrBefore.ts',
  'plugin/weekday': './src/plugin/weekday.ts',
  'plugin/weekYear': './src/plugin/weekYear.ts',
  'plugin/objectSupport': './src/plugin/objectSupport.ts',
  'plugin/arraySupport': './src/plugin/arraySupport.ts',
  'plugin/bigIntSupport': './src/plugin/bigIntSupport.ts',
  'plugin/minMax': './src/plugin/minMax.ts',
  'plugin/toArray': './src/plugin/toArray.ts',
  'plugin/toObject': './src/plugin/toObject.ts',
  'plugin/updateLocale': './src/plugin/updateLocale.ts',
  'plugin/preParsePostFormat': './src/plugin/preParsePostFormat.ts',
  'plugin/badMutable': './src/plugin/badMutable.ts',
  'plugin/isLeapYear': './src/plugin/isLeapYear.ts',
  'plugin/dayOfYear': './src/plugin/dayOfYear.ts',
  'plugin/isToday': './src/plugin/isToday.ts',
  'plugin/isTomorrow': './src/plugin/isTomorrow.ts',
  'plugin/isYesterday': './src/plugin/isYesterday.ts',
  'plugin/pluralGetSet': './src/plugin/pluralGetSet.ts',
  'plugin/buddhistEra': './src/plugin/buddhistEra.ts',
  'plugin/negativeYear': './src/plugin/negativeYear.ts',
  'locale/intl': './src/locale/intl.ts',
};

const moduleTargets = (id: string, entry: Record<string, string>, autoExternal = true) => [
  { id: `${id}-esm`, autoExternal, bundle: true, format: 'esm' as const, syntax: 'es2022' as const, source: { entry } },
  { id: `${id}-cjs`, autoExternal, bundle: true, format: 'cjs' as const, syntax: 'es2022' as const, source: { entry } },
];

export default defineConfig({
  lib: [
    ...moduleTargets('core', { index: './src/index.ts' }),
    ...moduleTargets('context', { context: './src/context.ts' }),
    ...moduleTargets('polyfill', { polyfill: './src/polyfill.ts' }, false),
    ...moduleTargets('full', { full: './src/full.ts' }),
    ...moduleTargets('plugins', pluginEntries),
    {
      id: 'umd-core',
      bundle: true,
      format: 'umd',
      syntax: 'es2022',
      umdName: 'temday',
      source: { entry: { core: './src/index.ts' } },
      output: { target: 'web', distPath: { root: './dist/umd' }, filename: { js: '[name].umd.min.js' } },
    },
    {
      id: 'umd-context',
      bundle: true,
      format: 'umd',
      syntax: 'es2022',
      umdName: 'temdayContext',
      source: { entry: { context: './src/context.ts' } },
      output: { target: 'web', distPath: { root: './dist/umd' }, filename: { js: '[name].umd.min.js' } },
    },
    {
      id: 'umd-polyfill',
      autoExternal: false,
      bundle: true,
      format: 'umd',
      syntax: 'es2022',
      umdName: 'temdayPolyfill',
      source: { entry: { polyfill: './src/polyfill.ts' } },
      output: { target: 'web', distPath: { root: './dist/umd' }, filename: { js: '[name].umd.min.js' } },
    },
    {
      id: 'umd-full',
      bundle: true,
      format: 'umd',
      syntax: 'es2022',
      umdName: 'temday',
      source: { entry: { full: './src/full.ts' } },
      output: { target: 'web', distPath: { root: './dist/umd' }, filename: { js: '[name].umd.min.js' } },
    },
  ],
  output: { distPath: { root: './dist' }, sourceMap: false, minify: true },
});
