import { defineConfig } from 'vitepress';

const base = process.env.DOCS_BASE ?? '/';

export default defineConfig({
  title: 'temday',
  description: 'Temporal-native date handling with a compact Day.js-compatible core.',
  base,
  cleanUrls: true,
  lastUpdated: true,
  // The site is intentionally dark. `force-dark` also makes VitePress select
  // Shiki's dark token palette, instead of rendering light syntax colors on
  // our dark code surfaces.
  appearance: 'force-dark',
  locales: {
    root: { label: 'English', lang: 'en-US' },
    zh: {
      label: '简体中文',
      lang: 'zh-CN',
      link: '/zh/',
      themeConfig: {
        nav: [{ text: 'API', link: '/zh/reference/core-api' }],
        sidebar: {
          '/zh/': [
            { text: '介绍', collapsed: true, items: [{ text: '为什么是 temday', link: '/zh/guide/why-temday' }, { text: '安装', link: '/zh/guide/installation' }, { text: '选择入口', link: '/zh/guide/package-entries' }, { text: 'Node.js', link: '/zh/installation/node' }, { text: '浏览器', link: '/zh/installation/browser' }, { text: 'TypeScript', link: '/zh/guide/typescript' }, { text: '开始使用', link: '/zh/guide/getting-started' }] },
            { text: '解析', collapsed: true, items: [{ text: '当前时间', link: '/zh/parsing/default#current-time' }, { text: 'Temporal', link: '/zh/parsing/default#temporal' }, { text: '字符串', link: '/zh/parsing/default#string' }, { text: '字符串 + 格式', link: '/zh/parsing/default#string-format' }, { text: 'Unix 时间戳', link: '/zh/parsing/default#unix-timestamp' }, { text: 'Date 对象', link: '/zh/parsing/default#date-object' }, { text: 'UTC', link: '/zh/parsing/default#utc-input' }, { text: '对象', link: '/zh/parsing/default#object-input' }, { text: '数组', link: '/zh/parsing/default#array-input' }, { text: 'temday 对象', link: '/zh/parsing/default#temday-instance' }] },
            { text: '取值/赋值', collapsed: true, items: [{ text: '取值/赋值', link: '/zh/get-set/' }, { text: 'Millisecond', link: '/zh/get-set/#millisecond' }, { text: 'Second', link: '/zh/get-set/#second' }, { text: 'Minute', link: '/zh/get-set/#minute' }, { text: 'Hour', link: '/zh/get-set/#hour' }, { text: 'Date of Month', link: '/zh/get-set/#date-of-month' }, { text: 'Day of Week', link: '/zh/get-set/#day-of-week' }, { text: 'Day of Week (Locale Aware)', link: '/zh/get-set/calendar#locale-weekday' }, { text: 'ISO Day of Week', link: '/zh/get-set/calendar#iso-weekday' }, { text: '每年中的第几天', link: '/zh/get-set/calendar#day-of-year' }, { text: 'Week of Year', link: '/zh/get-set/calendar#week-of-year' }, { text: 'Week of Year (ISO)', link: '/zh/get-set/calendar#iso-week' }, { text: 'Month', link: '/zh/get-set/#month' }, { text: 'Quarter', link: '/zh/get-set/calendar#quarter' }, { text: 'Year', link: '/zh/get-set/#year' }, { text: 'Week Year', link: '/zh/get-set/calendar#week-year' }, { text: 'Week Year (ISO)', link: '/zh/get-set/calendar#iso-week-year' }, { text: 'Weeks In Year (ISO)', link: '/zh/get-set/calendar#iso-weeks-in-year' }, { text: 'Get', link: '/zh/get-set/#get' }, { text: 'Set', link: '/zh/get-set/#set' }, { text: 'Maximum', link: '/zh/manipulation/immutable#maximum' }, { text: 'Minimum', link: '/zh/manipulation/immutable#minimum' }] },
            { text: '操作', collapsed: true, items: [{ text: '操作', link: '/zh/manipulation/' }, { text: 'Add', link: '/zh/manipulation/#add' }, { text: 'Subtract', link: '/zh/manipulation/#subtract' }, { text: 'Start of Unit of Time', link: '/zh/manipulation/#start-of' }, { text: 'End of Unit of Time', link: '/zh/manipulation/#end-of' }, { text: 'Local', link: '/zh/timezone/plugins#local' }, { text: 'UTC', link: '/zh/timezone/plugins#utc' }, { text: 'UTC offset', link: '/zh/timezone/plugins#utc-offset' }] },
            { text: '显示', collapsed: true, items: [{ text: '显示', link: '/zh/display/' }, { text: 'Format', link: '/zh/display/#format' }, { text: 'Time from now', link: '/zh/display/relative-time#from-now' }, { text: 'Time from X', link: '/zh/display/relative-time#from' }, { text: 'Time to now', link: '/zh/display/relative-time#to-now' }, { text: 'Time to X', link: '/zh/display/relative-time#to' }, { text: 'Calendar-time', link: '/zh/display/relative-time#calendar-time' }, { text: 'Difference', link: '/zh/query/#diff' }, { text: 'Unix 时间戳（毫秒）', link: '/zh/display/#unix-milliseconds' }, { text: 'Unix 时间戳', link: '/zh/display/#unix-seconds' }, { text: '月份中天数', link: '/zh/get-set/#days-in-month' }, { text: 'As JavaScript Date', link: '/zh/display/#as-javascript-date' }, { text: 'As Array', link: '/zh/display/#as-array' }, { text: 'As JSON', link: '/zh/display/#as-json' }, { text: 'As ISO 8601 String', link: '/zh/display/#as-iso-8601-string' }, { text: 'As Object', link: '/zh/display/#as-object' }, { text: 'As String', link: '/zh/display/#as-string' }] },
            { text: '查询', collapsed: true, items: [{ text: '查询', link: '/zh/query/' }, { text: 'Is Before', link: '/zh/query/#is-before' }, { text: 'Is Same', link: '/zh/query/#is-same' }, { text: 'Is After', link: '/zh/query/#is-after' }, { text: 'Is Same or Before', link: '/zh/query/plugins#is-same-or-before' }, { text: 'Is Same or After', link: '/zh/query/plugins#is-same-or-after' }, { text: 'Is Between', link: '/zh/query/plugins#is-between' }, { text: 'Is a temday', link: '/zh/query/#is-a-temday' }, { text: 'Is Leap Year', link: '/zh/query/plugins#is-leap-year' }] },
            { text: '国际化 (i18n)', collapsed: true, items: [{ text: '国际化 (i18n)', link: '/zh/display/i18n' }, { text: '加载语言配置 (Node.js)', link: '/zh/display/i18n#load-node' }, { text: '加载语言配置 (浏览器)', link: '/zh/display/i18n#load-browser' }, { text: '改变语言配置 (全局)', link: '/zh/display/i18n#change-global-locale' }, { text: '改变语言配置 (当前实例)', link: '/zh/display/i18n#change-instance-locale' }, { text: '查看当前语言配置', link: '/zh/display/i18n#current-locale' }, { text: '列出当前语言的月份和周', link: '/zh/display/i18n#list-months-and-weekdays' }, { text: '获取语言配置的属性', link: '/zh/display/i18n#locale-properties' }] },
            { text: '插件和上下文', collapsed: true, items: [{ text: '插件机制', link: '/zh/plugins/' }, { text: '上下文机制', link: '/zh/timezone/' }, { text: 'CustomParseFormat', link: '/zh/plugins/custom-parse-format' }, { text: 'localeData', link: '/zh/plugins/locale-data' }, { text: 'localizedFormat', link: '/zh/plugins/localized-format' }, { text: 'advancedFormat', link: '/zh/plugins/advanced-format' }, { text: 'parserPipeline', link: '/zh/plugins/parser-pipeline' }, { text: 'tokenRegistry', link: '/zh/plugins/token-registry' }, { text: 'UTC', link: '/zh/plugins/utc' }, { text: 'Timezone', link: '/zh/plugins/timezone' }, { text: 'relativeTime', link: '/zh/plugins/relative-time' }, { text: 'Duration', link: '/zh/plugins/duration' }, { text: 'Calendar', link: '/zh/plugins/calendar' }, { text: 'weekOfYear', link: '/zh/plugins/week-of-year' }, { text: 'isoWeek', link: '/zh/plugins/iso-week' }, { text: 'quarterOfYear', link: '/zh/plugins/quarter-of-year' }, { text: 'isBetween', link: '/zh/plugins/is-between' }, { text: 'objectSupport', link: '/zh/plugins/object-support' }, { text: 'arraySupport', link: '/zh/plugins/array-support' }, { text: 'minMax', link: '/zh/plugins/min-max' }, { text: 'badMutable', link: '/zh/plugins/bad-mutable' }] },
            { text: '和 Day.js 的差异', collapsed: true, items: [{ text: '总览', link: '/zh/reference/compatibility' }, { text: '解析规则', link: '/zh/reference/compatibility#解析规则' }, { text: '国际化与语言包', link: '/zh/reference/compatibility#国际化与语言包' }, { text: '插件加载与实例识别', link: '/zh/reference/compatibility#插件加载与实例识别' }, { text: '全局定制', link: '/zh/reference/compatibility#全局定制' }, { text: 'Duration 与本地化显示', link: '/zh/reference/compatibility#duration-与本地化显示' }] },
          ],
        },
        outline: false,
      },
    },
  },
  head: [
    ['meta', { name: 'theme-color', content: '#111827' }],
    ['meta', { name: 'og:type', content: 'website' }],
    ['link', { rel: 'icon', href: `${base}temday-orbit.svg`, type: 'image/svg+xml' }],
  ],
  themeConfig: {
    logo: '/temday-orbit.svg',
    nav: [
      { text: 'API', link: '/reference/core-api' },
    ],
    sidebar: {
      '/': [
        { text: 'Introduction', collapsed: true, items: [{ text: 'Why temday', link: '/guide/why-temday' }, { text: 'Installation', link: '/guide/installation' }, { text: 'Choose an import', link: '/guide/package-entries' }, { text: 'Node.js', link: '/installation/node' }, { text: 'Browser', link: '/installation/browser' }, { text: 'TypeScript', link: '/guide/typescript' }, { text: 'Getting started', link: '/guide/getting-started' }] },
        { text: 'Parse', collapsed: true, items: [{ text: 'Now', link: '/parsing/default#current-time' }, { text: 'Temporal', link: '/parsing/default#temporal' }, { text: 'String', link: '/parsing/default#string' }, { text: 'String + format', link: '/parsing/default#string-format' }, { text: 'Unix timestamp', link: '/parsing/default#unix-timestamp' }, { text: 'Date object', link: '/parsing/default#date-object' }, { text: 'UTC', link: '/parsing/default#utc-input' }, { text: 'Object', link: '/parsing/default#object-input' }, { text: 'Array', link: '/parsing/default#array-input' }, { text: 'temday object', link: '/parsing/default#temday-instance' }] },
        { text: 'Get/Set', collapsed: true, items: [{ text: 'Get/Set', link: '/get-set/' }, { text: 'Millisecond', link: '/get-set/#millisecond' }, { text: 'Second', link: '/get-set/#second' }, { text: 'Minute', link: '/get-set/#minute' }, { text: 'Hour', link: '/get-set/#hour' }, { text: 'Date of month', link: '/get-set/#date-of-month' }, { text: 'Day of week', link: '/get-set/#day-of-week' }, { text: 'Locale weekday', link: '/get-set/calendar#locale-weekday' }, { text: 'ISO weekday', link: '/get-set/calendar#iso-weekday' }, { text: 'Day of year', link: '/get-set/calendar#day-of-year' }, { text: 'Week of year', link: '/get-set/calendar#week-of-year' }, { text: 'ISO week', link: '/get-set/calendar#iso-week' }, { text: 'Month', link: '/get-set/#month' }, { text: 'Quarter', link: '/get-set/calendar#quarter' }, { text: 'Year', link: '/get-set/#year' }, { text: 'Week year', link: '/get-set/calendar#week-year' }, { text: 'ISO week year', link: '/get-set/calendar#iso-week-year' }, { text: 'ISO weeks in year', link: '/get-set/calendar#iso-weeks-in-year' }, { text: 'Get', link: '/get-set/#get' }, { text: 'Set', link: '/get-set/#set' }, { text: 'Maximum', link: '/manipulation/immutable#maximum' }, { text: 'Minimum', link: '/manipulation/immutable#minimum' }] },
        { text: 'Manipulate', collapsed: true, items: [{ text: 'Manipulate', link: '/manipulation/' }, { text: 'Add', link: '/manipulation/#add' }, { text: 'Subtract', link: '/manipulation/#subtract' }, { text: 'Start of unit', link: '/manipulation/#start-of' }, { text: 'End of unit', link: '/manipulation/#end-of' }, { text: 'Local', link: '/timezone/plugins#local' }, { text: 'UTC', link: '/timezone/plugins#utc' }, { text: 'UTC offset', link: '/timezone/plugins#utc-offset' }] },
        { text: 'Display', collapsed: true, items: [{ text: 'Display', link: '/display/' }, { text: 'Format', link: '/display/#format' }, { text: 'Time from now', link: '/display/relative-time#from-now' }, { text: 'Time from X', link: '/display/relative-time#from' }, { text: 'Time to now', link: '/display/relative-time#to-now' }, { text: 'Time to X', link: '/display/relative-time#to' }, { text: 'Calendar time', link: '/display/relative-time#calendar-time' }, { text: 'Difference', link: '/query/#diff' }, { text: 'Unix milliseconds', link: '/display/#unix-milliseconds' }, { text: 'Unix timestamp', link: '/display/#unix-seconds' }, { text: 'Days in month', link: '/get-set/#days-in-month' }, { text: 'As JavaScript Date', link: '/display/#as-javascript-date' }, { text: 'As array', link: '/display/#as-array' }, { text: 'As JSON', link: '/display/#as-json' }, { text: 'As ISO 8601 string', link: '/display/#as-iso-8601-string' }, { text: 'As object', link: '/display/#as-object' }, { text: 'As string', link: '/display/#as-string' }] },
        { text: 'Query', collapsed: true, items: [{ text: 'Query', link: '/query/' }, { text: 'Is before', link: '/query/#is-before' }, { text: 'Is same', link: '/query/#is-same' }, { text: 'Is after', link: '/query/#is-after' }, { text: 'Is same or before', link: '/query/plugins#is-same-or-before' }, { text: 'Is same or after', link: '/query/plugins#is-same-or-after' }, { text: 'Is between', link: '/query/plugins#is-between' }, { text: 'Is a temday', link: '/query/#is-a-temday' }, { text: 'Is leap year', link: '/query/plugins#is-leap-year' }] },
        { text: 'Internationalization', collapsed: true, items: [{ text: 'i18n', link: '/display/i18n' }, { text: 'Load locale (Node.js)', link: '/display/i18n#load-node' }, { text: 'Load locale (browser)', link: '/display/i18n#load-browser' }, { text: 'Change locale (global)', link: '/display/i18n#change-global-locale' }, { text: 'Change locale (instance)', link: '/display/i18n#change-instance-locale' }, { text: 'Current locale', link: '/display/i18n#current-locale' }, { text: 'List months and weekdays', link: '/display/i18n#list-months-and-weekdays' }, { text: 'Locale properties', link: '/display/i18n#locale-properties' }] },
        { text: 'Plugins and context', collapsed: true, items: [{ text: 'Plugin mechanism', link: '/plugins/' }, { text: 'Context mechanism', link: '/timezone/' }, { text: 'More plugins', link: '/plugins/more' }] },
        { text: 'Differences from Day.js', collapsed: true, items: [{ text: 'Overview', link: '/reference/compatibility' }, { text: 'Parsing', link: '/reference/compatibility#parsing' }, { text: 'Internationalization', link: '/reference/compatibility#internationalization' }, { text: 'Duration and display', link: '/reference/compatibility#duration-and-localized-display' }] },
      ],
    },
    outline: false,
  },
});
